<img src="images/vgopalan.jpg" />
<h2>Dr. Venkat Gopalan</h2>
<p>Ribonuclease P (RNase P) is a ubiquitous and essential ribonucleoprotein (RNP) involved in 5Õ
   maturation of transfer RNAs (tRNAs). Bacterial RNase P consists of a catalytic RNA subunit and a
   protein cofactor. While the RNA subunits of most archaeal and all eukaryal RNase P contain
   several of the critical and conserved secondary structural elements present in their bacterial
   counterpart, they are not catalytically active in vitro in the absence of their multiple protein
   subunits, whose number varies from four to ten depending on&hellip;
   <a href="http://www.biosci.ohio-state.edu/%7evgopalan/index2.html">more</a>.</p>