<h1>New York Times and the Introductory Biology Program</h1>
<p>Ongoing efforts to improve the science education curriculum in grades K&ndash;12 over the last
   decade resulting in explicit statements of learning objectives in the form of science education
   benchmarks or standards have compressed the K&ndash;16 science education curriculum of old into
   K&ndash;12.</p>
<p>This permits, indeed requires, the college introductory science community to re-assess its
   learning objectives for its students, especially those taking non-science majors courses, those
   one or two college level courses that will determine largely if tomorrow's college graduates are
   and will remain scientifically literate citizens.</p>
<p>While, apparently daunting, such changes mean that college introductory science level courses no
   longer need to accomplish the &quot;concrete&quot; learning objectives of the now omnipresent
   6&ndash;9 science courses (although the need for remediation for some students is real). For
   example, it is unrealistic for a college science instructor to expect that s/he is posing for the
   very first time the question: &quot;What is science (or, for that matter its
   &quot;method&quot;)?&quot;</p>
<p>Accordingly, the Introductory Biology Program at the Ohio State University is in the ongoing
   process of curricular reform that takes builds on the increased factual base of students enrolling
   in our courses. These efforts have begun at the non-majors course level, due the urgency of
   graduating from college life-long learning, scientifically literate citizens.</p>
<p>Always present in our curricular learning objectives were lofty sounding goals, which we are now
   demonstrably better able to accomplish. These include:</p>
<ul>
 <li>relevancy of science you learn from this curriculum with your chosen profession and your
     personal life.</li>
 <li>connectedness/dependency between science and society and vice versa.</li>
 <li>science behind public policy issues (e.g. blastula screening for genetically-based Alzheimer's
     disease) is straightforward, the ethical issues behind the application of this technique is
     not.</li>
 <li>the objectivity of science can be compromised by political and economic agendae.</li>
</ul>
<p>At OSU, we have taken a first step in this curricular effort by requiring all students enrolled
   in IBP courses to subscribe to the The New York Times, a generally accepted "paper of record." OSU
   is not a agent of the New York Times (and vice-versa); several major reasons for this New York
   Times requirement include:</p>
<ul>
 <li>OSU participates in the New York Times &quot;readership program&quot; where all students living
     in dormitories (approximately 30% of the students enrolled in IBP courses) can receive a copy of
     the New York Times (or USA Today, or the local paper) at no added cost to them.</li>
 <li>The New York Times provides very appealing subscription rates to non-dorm students.</li>
 <li>No other possible &quot;paper of record&quot; has ever expressed interest in such
     collaboration.</li>
 <li>OSU has never asked for, and the New York Times has never offered, financial incentive (other
     than for student subscription rates) for this collaboration.</li>
</ul>