document.write('<div class=\"rss_feed\">');
document.write('<div class=\"rss_feed_title\">NYT &gt; Science</div>');
document.write('<ul class=\"rss_item_list\">');
document.write('<li class=\"rss_item\"><span class=\"rss_item_title\"><a class=\"rss_item_link\" href=\"http://www.nytimes.com/2008/02/20/science/space/20cnd-shuttle.html?ex=1361250000&amp;en=84f596a3f12a28f9&amp;ei=5088&amp;partner=rssnyt&amp;emc=rss\">Shuttle Lands Safely in Florida</a></span> <span class=\"rss_item_desc\">The shuttle ended a challenging 13-day mission to deliver a major new section to the International Space Station.</span></li>');
document.write('<li class=\"rss_item\"><span class=\"rss_item_title\"><a class=\"rss_item_link\" href=\"http://www.nytimes.com/2008/02/19/science/18frog.html?ex=1361250000&amp;en=7f9b7596ed095b27&amp;ei=5088&amp;partner=rssnyt&amp;emc=rss\">Paleontologists Reconstruct a Monster Frog</a></span> <span class=\"rss_item_desc\">Beelzebufo may be the largest frog that ever lived, weighing more than 10 pounds.</span></li>');
document.write('<li class=\"rss_item\"><span class=\"rss_item_title\"><a class=\"rss_item_link\" href=\"http://www.nytimes.com/2008/02/20/world/asia/20briefs-china.html?ex=1361250000&amp;en=8847ef28beaf18a7&amp;ei=5088&amp;partner=rssnyt&amp;emc=rss\">China Notes Pollution at Three Gorges Dam</a></span> <span class=\"rss_item_desc\">China&rsquo;s State Environmental Protection Administration said on Tuesday that water quality is barely improving in the main body of water behind the Three Gorges Dam.</span></li>');
document.write('<li class=\"rss_item\"><span class=\"rss_item_title\"><a class=\"rss_item_link\" href=\"http://www.nytimes.com/2008/02/19/science/19carb.html?ex=1361250000&amp;en=aee28c5b1efac3c2&amp;ei=5088&amp;partner=rssnyt&amp;emc=rss\">Scientists Would Turn Greenhouse Gas Into Gasoline</a></span> <span class=\"rss_item_desc\">Two scientists are introducing a concept, which they have patriotically named Green Freedom, for removing carbon dioxide from the air and turning it back into gasoline.</span></li>');
document.write('</ul>');
document.write('</div>');
