<img src="images/ddean.jpg" />
<h2>Dr. Donald Dean</h2>
<p>Protein engineering and biophysical analysis of insecticidal toxins is the major research interest
   in my laboratory. The ultimate goal of these studies is to understand the structure/function
   relationships of these proteins to create more specific and environmentally safer pesticides.</p>
<p>One project involves locating the functional domains of insecticidal crystal proteins (ICPs) of
   Bacillus thuringiensis.  Site-directed mutagenesis and homology switches of &hellip;
   <a href="http://www.biosci.ohio-state.edu/~biochem/faculty/Dean.html">more</a>.</p>