Late homework turned in within 24 hours after the due lab time is worth a maximum of half credit.
Any homework turned in past the 24-hour deadline is worth no credit. If possible, students should
deliver late homework directly to their TA in person. If that's not possible, students may deliver
late papers to their TA's mailbox in the IBP office (Smith 4040). Students must stamp the papers
with the day and time received and log it in as per posted instructions so IBP staff will know that
the paper is valid. A date stamp machine is available near the TA mailboxes. We enforce this policy
so that all students in the course are treated equally. Of course, these deadlines do not apply to
students who have arranged for make up work through their TA with a valid written excuse.