Unless you have a valid written excuse, two points are deducted for each day after the original due
date of the assignment. Any lab assignment turned in late must be placed in your TA's mailbox in
4040 Smith Lab between the hours of 7:30 am and 4:30 pm weekdays. You are required to record your
assignment in the assignment log notebook and date stamp your assignment with the date stamp
machine, both located just inside the SM 4040 doorway. Recording and stamping your assignment is for
your benefit to make sure your paper is received and gets proper credit. Assignments not recorded
and date stamped will be assumed as received on the day of TA pick up.