<img src="images/nbaker.jpg" />
<h2>Dr. Neil Baker</h2>
<p>My research is primarily concerned with secondary pathogens of the respiratory tract.
   Pseudomonas aeruginosa, has been of particular concern because of the high mortality rates
   associated with hospital-acquired infections and the high incidence in cystic fibrosis patients.
   More recently we have expanded our interests to other Gram-negative bacteria.</p>
<p>Recent investigations have concerned identification of the receptors on eukaryotic cells for
   bacteria. The primary interest has been&hellip;
   <a href="http://www.osumicrobiology.org/faculty/nbaker.htm">more</a>.</p>