<div class="GEC">
<h1>Goals and Objectives for the GEC Natural Science Category</h1>
<h2>Goals/Rationale:</h2>
<p>Courses in natural sciences foster an understanding of the principles, theories and methods of
   modern science, the relationship between science and technology, and the effects of science and
   technology on the environment.</p>
<h2>Learning Objectives:</h2>
<ol style="list-style-type:decimal">
 <li>Students understand the basic facts, principles, theories and methods of modern science.</li>
 <li>Students learn key events in the history of science.</li>
 <li>Students provide examples of the inter-dependence of scientific and technological
     developments.</li>
 <li>Students discuss social and philosophical implications of scientific discoveries and
     understand the potential of science and teaching to address problems of the contemporary
     world.</li>
</ol>
</div>