<? $name = 'Dr. Ralph Boerner'; ?>
<img src="images/rboerner.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>My research interests focus on ecosystem and landscape level analyses of forested regions in the
   north and south temperate zones, with special emphasis on the impacts of atmospheric deposition,
   management, fire, and landscape structure on the interchanges of carbon, nitrogen, and
   phosphorus among soils, plants, animals, and microbes. Techniques of plant ecophysiology, soil
   chemistry and biochemistry, and community analysis are&hellip;
   <a href="http://www.biosci.ohio-state.edu/~eeob/resints/res_boerner.html">more</a>.</p>