<? $name = 'Dr. Tien-Hsien Chang'; ?>
<img src="images/tchang.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>We are studying the functions of the ubiquitous DExD/H-box proteins, which are often referred
   to as RNA helicases or RNA unwindases.  These proteins are essential for all RNA-related
   biological processes such as pre-mRNA splicing, ribosomal biogenesis, mRNA export, translation,
   and RNA turnover.  Consequently, they are of central importance to the cellular genetic information
   flow.</p>
<p>Although initially thought to function in a manner similar to&hellip;
   <a href="http://www.osumolgen.org/faculty/chang.htm">more</a>.</p>