<? $name = 'Dr. Steve Chordas'; ?>
<img src="images/schordas.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>In addition to teaching for CLSE, I am a full time Public Health Entomologist for the Ohio
   Department of Health. We primarily do surveillance and testing for Vector-Borne Diseases in
   Ohio. We track outbreaks or incidence of diseases like West Nile Virus, Rocky Mountain Spotted
   Fever, you know &ndash; the fun stuff! Anything you can get from an arthropod, we are interested
   in investigating and testing them to see if the disease is present in the vectors in Ohio. My
   research interests&hellip;
   <a href="instructors/chordas.php">more</a>.</p>
