<? $name = 'Dr. Biao Ding'; ?>
<img src="images/bding.JPG" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>The eukaryotic cell has evolved highly elaborate subcellular organelles/structures that
   specialize in distinct biochemical/biophysical processes. The biogenesis of
   organelles/structures, progression of localized biochemical reactions and cellular integration
   of these processes involve extensive subcellular traffic and localization of a wide variety of
   molecules. Within an organelle, the spatially clustered biochemical reactions&hellip;
   <a href="http://www.biosci.ohio-state.edu/pcmb/osu_pcmb/people/ding.htm">more</a>.</p>