<img src="images/sfisher.jpg" />
<h2>Dr. Susan Fisher</h2>
<p>My research interests are in the general area of environmental toxicology with emphasis on the
   influence of physical factors on contaminant transfer from sediment into aquatic foodchains. I
   am also interested in factors which affect trophic transfer and in relating tissue levels of
   contaminants with the myriad of biological effects that they produce. Although not an insect,
   alien species such as the zebra mussel, has become a focus of my research with emphasis
   on&hellip; <a href="http://iris.biosci.ohio-state.edu/osuent/personnel/fisher.html">more</a>.</p>