<img src="images/chris_gough.jpg" />
<h2>Dr. Christopher Gough</h2>
<p>My research within the field of ecosystem ecology and plant physiological ecology focuses on
   understanding the relationship between forest carbon cycling and global change. Forests are an
   important component of the global carbon cycle, storing carbon in biomass, detritus, and soils.
   Plants remove carbon dioxide from the atmosphere, thereby absorbing anthropogenic greenhouse gas
   emissions and potentially &hellip;
   <a href="http://www.biosci.ohio-state.edu/~pcurtis/People/Christopher%20Gough/index.html">more</a>.</p>