<img src="images/thetherington.jpg" />
<h2>Dr. Tom Hetherington</h2>
<p>I have two major research focuses: (1) the function and evolution of sensory systems and the
   sensory behavior of amphibians and reptiles, and (2) the conservation biology of amphibians and
   reptiles. (1) One current project involves behavioral and functional studies of alternative
   hearing systems in amphibians and reptiles. Many amphibians and reptiles lack a standard
   tympanic middle ear and appear to rely on very different mechanisms for detecting sound.
   Information about these alternative systems is&hellip;
   <a href="">more</a>.</p>