<? $name = 'Dr. David Horn'; ?>
<img src="images/dhorn.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>My research emphasis has concentrated on the ecology of predator-prey and parasitoid-host
   interactions and application of this to biological control. Recent projects have included
   stochastic modeling of spider-mite predator-prey interactions and biological control of purple
   loosestrife with chrysomelid beetles. My current efforts are focused on assessing environmental
   impacts of&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnelsingle.asp?strid=306">more</a>.</p>