<img src="images/hklompen.gif" />
<h2>Dr. Hans Klompen</h2>
<p>My main research interests are in the systematics and evolution of mites. Within the general area
   I have migrated from trying to understand the quite specific host associations in sarcoptid mange
   mites, to biogeographical patterns in ticks, to basal systematics of the entire order
   Parasitiformes. I try to approach these questions from several directions, combining morphological
   and molecular data sets in order to develop&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnelsingle.asp?strid=2910">more</a>.</p>