<? $name = 'Dr. Joseph Kovach'; ?>
<img src="images/jkovach.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>As Integrated Pest Management Coordinator, I work closely with research and extension faculty in
   entomology, plant pathology, and horticulture and crop science to develop and implement programs
   that use ecological principles to better mange pest populations. My research interests are in
   developing sustainable management methods for fruit pests and the multicolored Asian lady
   beetle, Harmonia axyridis&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnel/kovach.html">more</a>.</p>