<? $name = 'Dr. Roman Lanno'; ?>
<img src="images/rlanno.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>The primary focus of research in our laboratory lies in applied and theoretical aspects of
   determining the bioavailability of chemicals in the environment, particularly in soil systems.
   We strive to understand and interpret bioavailability as it relates to 1) soil-chemical
   interactions; 2) interaction, uptake, and distribution within organisms; 3) toxicity and
   bioaccumulation at the&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnelsingle.asp?strid=1820">more</a>.</p>