<? $name = 'Dr. Richard Sayre'; ?>
<img src="images/rsayre.gif" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>There are three major research programs in our lab including; 1) molecular studies on primary
   photochemical processes in photosystem II complexes of chloroplasts, 2) metabolic engineering of
   cyanogensis and starch in the tropical root crop cassava, and 3) the biochemical
   characterization and genetic manipulation of&hellip;
   <a href="http://www.biosci.ohio-state.edu/~plantbio/osu_pcmb/people/sayre.htm">more</a>.</p>