<? $name = 'Dr. Amanda Simcox'; ?>
<img src="images/asimcox.JPG" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>We study EGF receptor signaling in Drosophila development focusing mainly on the ligand called
   Vein, which by similarity is the fly neuregulin. Neuregulins are activators of the erbB
   receptors in vertebrates and play important roles in development and disease. We are currently
   characterizing the mechanisms that control biological activity of Vein. The promoter region is
   being analyzed and this has revealed a significant&hellip;
   <a href="http://www.biosci.ohio-state.edu/%7emolgen/html/simcox-_more_info.html">more</a>.</p>