<? $name = 'Dr. David Stetson'; ?>
<img src="images/dstetson.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>My research efforts have concentrated on defining the cullular mechanisms of ion transport,
   particularly epithelian H+ secretion, and the means by which cells involved in ion transport
   compensate for changes in physiologic demand. Turtle and toad urinary bladders are used as
   model systems for the mammalian renal collecting ducts, major sites of active H+ secretion in
   the kidneys. A wide range of research tools are used to&hellip;
   <a href="http://excelsior.biosci.ohio-state.edu/~eeob/drupal//?q=userpages/38">more</a>.</p>