<? $name = 'Dr. Richard Swenson'; ?>
<img src="images/rswenson.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>Our research is focused primarily on the study of a family of proteins that use derivatives of
   riboflavin (vitamin B2) as essential cofactors or coenzymes for their biological activity. Our
   emphasis is the investigation of the structure of the protein, its influence on the chemical and
   oxidation-reduction and other chemical properties of the bound flavin cofactor, and the role of
   the cofactor in catalysis and/or electron transfer. Flavoproteins are often an integral part
   of&hellip;
   <a href="http://www.biosci.ohio-state.edu/~rswenson/research.html">more</a>.</p>