<img src="images/mweinstein.jpg" />
<h2>Dr. Michael Weinstein</h2>
<p>Smad proteins are the intracellular mediators of the transforming growth factor beta (TGF-b)
   superfamily. My laboratory will be focusing on role of Smad genes in the control of mammalian
   development, disease, and cancer using primarily knockout and transgenic mice. Our research has
   shown that Smad2 and Smad 4 are required for gastrulation, while Smad5 is involved in
   angiogenesis and crainiofacial development. Smad3 appears to mediate&hellip;
   <a href="http://cancergenetics.med.ohio-state.edu/2742.cfm">more</a>.</p>