<? $name = 'Dr. John Wenzel'; ?>
<img src="images/jwenzel.jpg" alt="<?= $name ?>"/>
<h2><?= $name ?></h2>
<p>Studies of behavioral evolution will reach their maturity when we can distinguish variation that
   reflects phylogenetic history from that which does not. To this end, cladistic views of behavior
   must be compared with more main-stream evidence of evolutionary history. My DNA laboratory
   offers data complementary to behavioral patterns observed&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnelsingle.asp?strid=2916">more</a>.</p>
<a href="http://ucat.osu.edu/dosomethinggreat/wenzel.html">Dr. John Wenzel explains
   why he teaches introductory courses.</a>
