<img src="images/twilson.jpg" />
<h2>Dr. Tom Wilson</h2>
<p>In my laboratory we study two areas of entomology. The first focuses on the endocrine control
   of development and reproduction in insects. We study two hormones, juvenile hormone (JH) and
   ecdysone, that control metamorphosis, and we use both <i>Drosophila melanogaster</i> and the
   mosquito <i>Aedes aegypti</i> as our research insects. We have identified one gene,
   Methoprene-tolerant (Met), involved in the molecular action of JH. Methoprene is one of several
   insecticides that&hellip;
   <a href="http://www.oardc.ohio-state.edu/entomology/personnelsingle.asp?strid=2917">more</a>.</p>