<ul>
 <li><a href="courses/101/">Biology 101</a></li>
 <li><a href="courses/102/">Biology 102</a></li>
 <li><a href="courses/113/">Biology 113</a></li>
 <li><a href="courses/114/">Biology 114</a></li>
 <li><a href="courses/115/">Honors Biology&nbsp;115</a></li>
 <li><a href="courses/116/">Honors Biology&nbsp;116</a></li>
 <li class="hr">&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;</li>
 <li><a href="textbooks/">Textbooks</a></li>
</ul>